### PR TITLE
Added configurable sign block state & block colors

### PR DESCRIPTION
**Pull request by montlikadani**
If you do not want the colors to be edited, then delete the colors just to know the block.
I have not found the configuration version verification code anywhere. :(

### CODE REVIEW

**Comment by Plajer** [comment]
Really useless

**Comment by montlikadani** [comment]
What do I mean? It is not good at all?

**Comment by Plajer** [comment]
You complicate really simple feature.

**Comment by montlikadani** [comment]
This is not complicated. It is more useful because at least can edit the user's features that need.

**Comment by Plajer** [comment]
This part of code will be changed as of 1.13 update.

**Comment by montlikadani** [comment]
Why you can close this, when I do it?

**Comment by Plajer** [comment]
This part of code will be changed as of 1.13 update.
--

**Comment by Plajer** [comment]
wat formatting

**Pull request closed without merging**
